import { describe, it, expect, beforeEach, vi } from 'vitest';

vi.hoisted(() => {
  process.env.DATABASE_URL = 'postgresql://localhost:5432/sync_erp_test';
});

import {
  recordBotSentMessageId,
  isBotSentMessage,
  clearBotSentMessageIds,
  isInternalStaff,
} from '../../src/bot/baileys';

describe('Bot Message Tracking & Owner Protection', () => {
  beforeEach(() => {
    clearBotSentMessageIds();
  });

  describe('recordBotSentMessageId & isBotSentMessage', () => {
    it('records message IDs generated by bot outbound sends', () => {
      expect(isBotSentMessage('msg-bot-123')).toBe(false);
      recordBotSentMessageId('msg-bot-123');
      expect(isBotSentMessage('msg-bot-123')).toBe(true);
    });

    it('returns false for manual owner messages (not recorded by bot)', () => {
      recordBotSentMessageId('msg-bot-456');
      expect(isBotSentMessage('msg-owner-manual-789')).toBe(false);
      expect(isBotSentMessage(null)).toBe(false);
      expect(isBotSentMessage(undefined)).toBe(false);
      expect(isBotSentMessage('')).toBe(false);
    });

    it('ignores empty or unknown message IDs when recording', () => {
      recordBotSentMessageId('');
      recordBotSentMessageId('unknown');
      expect(isBotSentMessage('')).toBe(false);
      expect(isBotSentMessage('unknown')).toBe(false);
    });
  });

  describe('Internal Staff Invariant Verification', () => {
    it('unconditionally identifies Admin 1 Sales Santi Mebel', () => {
      expect(isInternalStaff('6281249182155')).toBe(true);
      expect(isInternalStaff('081249182155')).toBe(true);
      expect(isInternalStaff('6281249182155@s.whatsapp.net')).toBe(true);
      expect(isInternalStaff('75432611295262@lid')).toBe(true);
    });

    it('unconditionally identifies Mas Don (Owner)', () => {
      expect(isInternalStaff('6285158858310')).toBe(true);
      expect(isInternalStaff('085158858310')).toBe(true);
    });
  });
});
