-- Enable Row Level Security on all tables
-- This blocks direct access via Supabase PostgREST API
-- All legitimate access goes through Railway API (Prisma)

-- Core tables
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Session" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Company" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CompanyMember" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Role" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Permission" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RolePermission" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SystemConfig" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DocumentSequence" ENABLE ROW LEVEL SECURITY;

-- Partner & Product tables
ALTER TABLE "Partner" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProductCategory" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Product" ENABLE ROW LEVEL SECURITY;

-- Order tables
ALTER TABLE "Order" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OrderItem" ENABLE ROW LEVEL SECURITY;

-- Inventory tables
ALTER TABLE "InventoryMovement" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Warehouse" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StockLayer" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Fulfillment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "FulfillmentItem" ENABLE ROW LEVEL SECURITY;

-- Finance tables
ALTER TABLE "Invoice" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "InvoiceItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Payment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Account" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "JournalEntry" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "JournalLine" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BankAccount" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CashTransaction" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CashTransactionItem" ENABLE ROW LEVEL SECURITY;

-- Audit & System tables
ALTER TABLE "AuditLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "IdempotencyKey" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SagaLog" ENABLE ROW LEVEL SECURITY;

-- Rental tables
ALTER TABLE "RentalItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RentalBundle" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RentalBundleComponent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RentalItemUnit" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RentalOrder" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RentalOrderExtension" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RentalOrderItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RentalOrderUnitAssignment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RentalDeposit" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RentalDepositAllocation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RentalReturn" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RentalPolicy" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RentalDamagePolicy" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ItemConditionLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CleaningLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CustomerRentalRisk" ENABLE ROW LEVEL SECURITY;

-- Note: No policies created = default deny for all PostgREST access
-- This is intentional since all access is through backend API via Prisma
